import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import React, {  useState } from 'react';
import Header from '../components/header';
import { ethers } from "ethers";

const data = [
  {
    id: 1,
    title: 'A first item - This is a dummy',
  },
  { 
    id: 2,
    title: 'A second item',
  },
  {
    id: 3,
    title: 'A third item',
  },
]


export default function Home() {
	const [tasks, setTasks] = useState("");
	const [todoList, setTodoList] = useState([]);
	const [taskCount, setTaskCount] = useState(0);
  const [account, setAccount] = useState("");


	const addTask = () => {
    if (tasks != "") {

      let task = {
        id: taskCount + 1,
        title: tasks,
        completed: false,
      }
      setTodoList([...todoList, task]);
      setTaskCount(taskCount + 1);
    } 
	};

	const toggleCompleted = (id) => {
    const newTasks = todoList.map((task) => {
      if (task.id === id) {
        task.completed = !task.completed;
      }
      return task;
    });
    setTodoList( newTasks );
  };

  const ifEmpty = () => {
    if (!todoList.length) {
      return (
        <>
          {data.map((item) => {
            return <li className="list-group-item" key={item.id}>{item.title}</li>
          })}
        </>
      )
    } else {
      return (
        <>
          {todoList?.map((item) => {
            return (
              <div className="form-check" key={item.id}>
                <input className="form-check-input" type="checkbox" 
                defaultChecked={item.completed} 
                onClick={() => toggleCompleted(item.id)}/>
                <label className={`form-check-label ${item.completed ? 'text-decoration-line-through' : ''}`} 
                  htmlFor="flexCheckChecked">
                  {item.title}
                </label>
              </div>
            )
          })}
        </>
      )
    }
  }
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" /> 
      </Head>
			<main>
				<Header />
				<div className="mt-4">
					<div className="w-50 m-auto border p-2">
						<h1 className="text-center mb-4">Todo List</h1>
						<div className="row mb-4">
							<div className="col-6">
              <ul className="list-group">
                {ifEmpty()}
              </ul>
              </div>
							<div className="col-6">
								<div className="">
									<div className="mb-3 row">
                    <div className="col-12">
                      <form
                      onSubmit={(event) => {
                        event.preventDefault()
                        addTask();
                        setTasks("")
                      }}
                      >
                        <input
                          type="text"
                          value={tasks}
                          className="form-control"
                          placeholder="Tell me what you want to do...."
                          onChange={(e) => {
                            setTasks(e.target.value);
                          }}
                        />
                        <input type="submit" hidden={true} />
                      </form>
                    </div>
                    {/* <div className="col-4 m-0">
                      <button className="btn btn-dark"
                      onClick={addTask}>
                        Add task
                      </button>
                    </div> */}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
